title: Welcome to my Homepage
author: DRAJARAM123
email: your-email@domain.com
description:  Food around the world. 
theme: minima

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
